kind: ConfigMap
apiVersion: v1

metadata:
   name: easy-shop-config
   namespace: easy-shop-ns
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://54.247.249.49/api"  # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_URL: "http://54.247.249.49"             # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_SECRET: "EH9Ojrs/CNCicrpGyFuIqqp4SF/XYDngmGqNLbLyoTU="
  JWT_SECRET: "523f0e2a9e127f118f0116cb6894306197425be7bc9f4773a775512d788ba7fe"
