apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secret
  namespace: easy-shop-ns
type: Opaque
stringData:
  NEXTAUTH_SECRET: "EH9Ojrs/CNCicrpGyFuIqqp4SF/XYDngmGqNLbLyoTU="
  JWT_SECRET: "523f0e2a9e127f118f0116cb6894306197425be7bc9f4773a775512d788ba7fe"
